pipeline:
  name: hcli-mvn-test
  identifier: hclimvntest
  projectIdentifier: tiagentdev
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: avijeetgradletest
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: false
            override: false
            paths: []
          buildIntelligence:
            enabled: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: env
              - step:
                  type: Run
                  name: Test
                  identifier: Run_1
                  spec:
                    connectorRef: DockerHub
                    image: maven:latest
                    shell: Sh
                    command: |-
                      curl -sSL -o /tmp/hcli https://storage.googleapis.com/harness-ti/hcli/vavijeet/hcli-linux-amd64
                      chmod +x /tmp/hcli
                      /tmp/hcli htx -- mvn test
        variables:
          - name: CI_ENABLE_BARE_METAL
            type: String
            description: ""
            required: false
            value: "true"
          - name: tls_client_certificate
            type: Secret
            description: ""
            required: false
            value: tls_client_certificate_text
          - name: tls_client_key
            type: Secret
            description: ""
            required: false
            value: tls_client_key_text
          - name: tls_certificate
            type: Secret
            description: ""
            required: false
            value: tls_certificate_text
          - name: sa_token
            type: Secret
            description: ""
            required: false
            value: account.bot_harness_account_token
          - name: CI_TI_V2_ENHANCED_FF
            type: String
            description: ""
            required: false
            value: "true"
          - name: HARNESS_TI_QA_ENV
            type: String
            description: ""
            required: false
            value: QA_ENV_ENABLED
          - name: CI_ENABLE_HCLI_FOR_TESTS
            type: String
            description: ""
            required: false
            value: "true"
